enabled: true
podAntiAffinity:
  enabled: true
image:
  # TODO: Update to your project's image repository
  repository: worlds-io/my-project-name
config:
  APP_LOG_LEVEL: "INFO"
  HTTP_ENDPOINT: "http://tracks-service-http:8080/graphql"
  TOKEN_ID: ""
  WS_ENDPOINT: "ws://tracks-service-http:8080/graphql"
env:
  # TODO: Update secret names and keys for your project
  - name: TOKEN_VALUE
    valueFrom:
      secretKeyRef:
        name: my-project-name
        key: TOKEN_VALUE
  - name: API_BEARER_TOKEN
    valueFrom:
      secretKeyRef:
        name: my-project-name
        key: API_BEARER_TOKEN
ports:
  - name: http
    containerPort: 8000
ingress:
  enabled: false
  hosts:
    - host: my-project-name
      paths:
        - path: /
          serviceName: my-project-name-http
          portNumber: 8000
